/*
 * Quiblo — a free, open source IPTV player.
 * Copyright (C) 2026 The Quiblo Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package dev.quiblo.core.data

import dev.quiblo.core.database.dao.FeedRowDao
import dev.quiblo.core.database.entity.FeedRowEntity
import dev.quiblo.core.model.FeedRowEntry
import dev.quiblo.core.model.FeedRowId
import dev.quiblo.core.model.MediaKind

/**
 * What the For You rows were, so the tab can draw them before it has worked them out again.
 *
 * **Both cached rows are expensive in a way the screen could not hide.** The popular rows match a
 * service's list against a sixty-thousand-title catalogue; the suggestions row scored the whole
 * catalogue on *every* emission of the metadata key, which is every time the tab was opened. The
 * answers do not change between one evening and the next, and a viewer was watching an empty shelf
 * while they were recomputed.
 *
 * **Per profile as well as per source.** Suggestions are one person's viewing, and a cache shared
 * across profiles is the leak `AC-PROF-02` exists to prevent.
 *
 * **Titles are remembered by the provider's stable key, never by row id.** A refresh deletes every
 * row of a source and reinserts it with a new autogenerated id, so ids remembered last night
 * resolve to nothing tonight — and on the popular rows "resolves to nothing" is drawn as
 * unavailable, which would turn every refresh into a top ten claiming the provider carries none of
 * it. Keys are still re-resolved on read: this table is authoritative about what was decided and
 * about nothing else.
 */
class FeedRowCacheRepository(
    private val dao: FeedRowDao,
    private val profiles: ProfileRepository,
    private val now: () -> Long = System::currentTimeMillis,
) {

    /** Every remembered row for this source and this viewer, in the order it was written. */
    suspend fun cached(sourceId: Long): Map<FeedRowId, List<FeedRowEntry>> =
        dao.rowsFor(profiles.activeProfileId, sourceId)
            .mapNotNull { it.toEntryOrNull() }
            .groupBy { it.rowId }

    /**
     * Replaces a ranking wholesale.
     *
     * A ranking is one answer arrived at all at once. Appending to last week's top ten would
     * produce a list of twenty in which position means two different things.
     */
    suspend fun replace(sourceId: Long, rowId: FeedRowId, entries: List<FeedRowEntry>) {
        val profileId = profiles.activeProfileId
        val stamp = now()
        dao.replaceRow(
            profileId = profileId,
            sourceId = sourceId,
            rowId = rowId.name,
            entries = entries.mapIndexed { index, entry ->
                entry.copy(position = index).toEntity(profileId, sourceId, stamp)
            },
        )
    }

    /**
     * Adds to the suggestions row rather than replacing it, and clears out what has gone stale.
     *
     * **Appending is the whole point.** A suggestions row that is rebuilt from scratch reshuffles
     * itself under the viewer: the same watch history scored twice, a fortnight apart, returns
     * mostly the same titles in a different order, and a shelf whose contents move for no visible
     * reason is a shelf nobody learns the shape of. So what was there stays where it was, and
     * anything new goes on the end.
     *
     * Two things are dropped rather than kept:
     *
     * - **A suggestion whose cause has been watched again since it was made.** Watching something
     *   a second time is the strongest signal this app gets, and it should move that title's
     *   suggestions rather than leave a fortnight-old answer standing in front of them. This is
     *   the only place in the row where order is allowed to change.
     * - **A suggestion whose title the catalogue no longer has.** A refresh can remove it, and a
     *   tile with nothing behind it is a tile that cannot be opened.
     *
     * @param fresh the newly scored suggestions, best first.
     * @param watchedSince when each watched title was last played, by title.
     * @param stillInCatalogue which of the cached stable keys resolved to a row just now.
     * @param limit how long the row may grow to. The oldest surviving entries are kept.
     */
    // Six parameters and every one of them is a different question: which source, which row, what
    // is new, what has been watched since, what still exists, and how long the row may get. A
    // holder around them would rename the list rather than shorten it.
    @Suppress("LongParameterList")
    suspend fun append(
        sourceId: Long,
        rowId: FeedRowId,
        fresh: List<FeedRowEntry>,
        watchedSince: Map<String, Long>,
        stillInCatalogue: Set<String>,
        limit: Int,
    ) {
        val profileId = profiles.activeProfileId
        val held = dao.rowsFor(profileId, sourceId).filter { it.rowId == rowId.name }

        val kept = held.filter { entry ->
            val causeWatchedAgain = entry.becauseOf
                ?.let { watchedSince[it] }
                ?.let { it > entry.builtAtEpochMillis } == true
            val key = entry.stableKey
            !causeWatchedAgain && key != null && key in stillInCatalogue
        }

        val keptKeys = kept.mapNotNull { it.stableKey }.toSet()
        val added = fresh.filter { it.stableKey != null && it.stableKey !in keptKeys }

        val stamp = now()
        val merged = (kept.mapNotNull { it.toEntryOrNull() } + added)
            .take(limit)
            .mapIndexed { index, entry -> entry.copy(position = index) }

        dao.replaceRow(
            profileId = profileId,
            sourceId = sourceId,
            rowId = rowId.name,
            // A kept entry keeps its own date. Restamping them all would make "watched again since
            // this was suggested" permanently false, which is the one thing that empties this row.
            entries = merged.map { entry ->
                val heldStamp = kept.firstOrNull { it.stableKey == entry.stableKey }?.builtAtEpochMillis
                entry.toEntity(profileId, sourceId, heldStamp ?: stamp)
            },
        )
    }

    /** Forgets everything for a source, for when the catalogue underneath it has been replaced. */
    suspend fun clearForSource(sourceId: Long) = dao.clearForSource(sourceId)

    private fun FeedRowEntity.toEntryOrNull(): FeedRowEntry? {
        val id = runCatching { FeedRowId.valueOf(rowId) }.getOrNull() ?: return null
        return FeedRowEntry(
            rowId = id,
            position = position,
            stableKey = stableKey,
            title = title,
            posterUrl = dev.quiblo.source.tmdb.TmdbClient.toHighResTmdbUrl(posterUrl, isBackdrop = false),
            kind = runCatching { MediaKind.valueOf(kind) }.getOrDefault(MediaKind.VOD),
            rank = rank,
            becauseOf = becauseOf,
        )
    }

    private fun FeedRowEntry.toEntity(profileId: Long, sourceId: Long, builtAt: Long) = FeedRowEntity(
        profileId = profileId,
        sourceId = sourceId,
        rowId = rowId.name,
        position = position,
        stableKey = stableKey,
        title = title,
        posterUrl = posterUrl,
        kind = kind.name,
        rank = rank,
        becauseOf = becauseOf,
        builtAtEpochMillis = builtAt,
    )
}
